asamuzaK/url2clipboard

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/css/popup.css
- src/html/popup.html
- src/js/background.js
- src/js/content.js
- src/js/popup.js
> Handle link within page

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/css/options.css
- src/img/icon.svg
- src/js/background.js
- src/js/clipboard.js
- src/js/options.js
- src/manifest.json
- src/options/options.html
> Add options

- src/_locales/zh_CN/messages.json
> Update zh_CN locale

- src/js/content.js
>  Parse canonical url

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/js/background.js
> Add Set of enabled formats

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/html/options.html
- src/js/clipboard.js
- src/mjs/background.js
- src/mjs/constant.js
> Add option to apply quick fix for Thunderbird bug

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/html/options.html
- src/js/clipboard.js
- src/manifest.json
- src/mjs/browser.js
- src/mjs/constant.js
- src/mjs/main.js
- src/mjs/options-main.js
- test/browser.test.js
- test/main.test.js
- test/options-main.test.js
> Add notification

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/js/content.js
- src/manifest.json
- src/mjs/background.js
- src/mjs/constant.js
- src/mjs/main.js
- test/main.test.js
> Add command handler

- src/_locales/zh_CN/messages.json
> update zh locale

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/html/options.html
- src/mjs/constant.js
- src/mjs/format.js
- src/mjs/main.js
- src/mjs/popup-main.js
- test/main.test.js
- test/popup-main.test.js
> Add separate lines option

- src/html/popup.html
- src/js/clipboard.js
- src/mjs/clipboard.js
- src/mjs/common.js
- src/mjs/format.js
- src/mjs/main.js
- src/mjs/notify.js
- src/mjs/popup-main.js
- test/clipboard.test.js
- test/common.test.js
- test/format.test.js
- test/main.test.js
- test/notify.test.js
- test/popup-main.test.js
> Async write

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/js/clipboard.js
- src/mjs/format.js
- src/mjs/main.js
- src/mjs/notify.js
- src/mjs/popup-main.js
- test/main.test.js
- test/notify.test.js
- test/popup-main.test.js
> Add format title

- src/js/content.js
- test/content.test.js
- test/mocha/setup.js
> Refactor content.js and add tests 

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/html/popup.html
- src/mjs/constant.js
- src/mjs/format.js
- src/mjs/main.js
- src/mjs/popup-main.js
- test/format.test.js
- test/main.test.js
- test/popup-main.test.js
> Add Copy Other Tabs URLs menu

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/html/options.html
- src/mjs/constant.js
- src/mjs/main.js
- src/mjs/popup-main.js
- test/main.test.js
- test/popup-main.test.js
> Opt-in prefer canonical URL

- src/mjs/background.js
- src/mjs/format.js
- src/mjs/main.js
- src/mjs/menu.js
- test/format.test.js
- test/main.test.js
- test/menu.test.js
> Fix Copy Link menu handling

- src/mjs/main.js
- test/main.test.js
> Fix command handler

- package.json
> Fix bundle script

- src/mjs/main.js
- test/main.test.js
> Change the order of content

- modules/blink.js
> Temporary remove persistent

- src/mjs/main.js
- test/main.test.js
> Update error handling

- src/mjs/format.js
- src/mjs/main.js
- test/format.test.js
- test/main.test.js
> Add new line option

- src/html/popup.html
- src/mjs/popup-main.js
- test/popup-main.test.js
> Hide link menu if data is not type of link

- src/mjs/main.js
- test/main.test.js
> Exclude highlighted tabs

- src/mjs/exec-copy.js
- src/mjs/main.js
- test/exec-copy.test.js
- test/main.test.js
Ref  https://github.com/asamuzaK/url2clipboard/issues/128#issuecomment-1496773412
> Split copy function into single file

- src/manifest.json
- src/mjs/icon.js
- src/mjs/menu.js
> Migrate to MV3

- src/js/context-info.js
- test/context-info.test.js
> Use innerText if possible

- src/manifest.json
- src/mjs/icon.js
- src/mjs/menu.js
> Migrate to MV3 gecko (again)

- modules/blink.js
- src/manifest.json
- src/mjs/icon.js
- src/mjs/menu.js
> Back to MV2 for Gecko

- src/manifest.json
- src/mjs/background.js
- src/mjs/main.js
- test/main.test.js
- types/src/mjs/main.d.ts
> Add tabs.Tab to commands listener

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/html/options.html
- src/html/popup.html
- src/manifest.json
- src/mjs/constant.js
- src/mjs/format.js
- test/format.test.js
- test/main.test.js
- test/menu.test.js
> Support DocuWiki

- src/mjs/main.js
- src/mjs/popup-main.js
- test/main.test.js
- test/popup-main.test.js
> Add new prop `editedText` in popup

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/html/options.html
- src/html/popup.html
- src/mjs/constant.js
- src/mjs/options-main.js
- src/mjs/options.js
- src/mjs/popup.js
- test/options-main.test.js
Follow up for #171 and some fixes
> Follow up  #171

- src/mjs/main.js
- test/main.test.js
> Add fallback in handleCmd

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh_CN/messages.json
- src/html/options.html
- src/html/popup.html
- src/manifest.json
- src/mjs/constant.js
- src/mjs/format.js
- test/format.test.js
- test/main.test.js
- test/menu.test.js
> Add CSV support
